
[functions.create-active-session]
enabled = true
verify_jwt = true
import_map = "./functions/create-active-session/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-active-session/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-active-session/*.html" ]

[functions.pdf-to-json]
enabled = true
verify_jwt = true
import_map = "./functions/pdf-to-json/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/pdf-to-json/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/pdf-to-json/*.html" ]

